apiVersion: v1
kind: Service
metadata:
  name: gogs
  namespace: devops
  labels:
    app: gogs
spec:
  type: NodePort
  ports:
   - port: 3000
     protocol: TCP
     targetPort: 3000
     nodePort: 30101
     name: port-gogs-http
   - port: 22
     protocol: TCP
     targetPort: 22
     nodePort: 30102
     name: port-gogs-ssh
  selector:
   app: gogs